### ISSUE TITLE
Add autocompletion for tags

### ISSUE THREAD

**Issue by galfert** [skddc/webmarks#29]
To make it easier to re-use existing tags, it would be great to some form of autocompletion.

**Comment by skddc** [comment]
Also, an actual tag UI. :)

@galfert I suppose there are Ember addons for this kind of thing? Maybe you know (or have webmarked) a good one?

**Comment by skddc** [comment]
Started implementing this in 23b6152. Ui is done, but no real tags wired up yet.

I was thinking about how to approach this, as you don't want to load all bookmarks when coming to `new` from the bookmarklet for example. I also don't want to store a new collection in remoteStorage (at least not unless we standardize tags in a module).

So perhaps storing a completely seperate key in `localStorage` when loading the bookmarks index could make sense. Then we could just retrieve that list in the new/edit routes. When storing the bookmark, we could update it as well, so that new tags are also contained immediately.

**Comment by galfert** [comment]
> Also, an actual tag UI. :)
> 
> @galfert I suppose there are Ember addons for this kind of thing? Maybe you know (or have webmarked) a good one?

I had searched for something some time ago. The only thing I found that looked half way feasible was https://www.npmjs.com/package/ember-tag-search-input

**Comment by galfert** [comment]
> So perhaps storing a completely seperate key in localStorage when loading the bookmarks index could make sense.

I think I like that approach.
