### ISSUE TITLE
do not require title field, auto fetch it

### ISSUE THREAD

**Issue by fkooman** [skddc/webmarks#53]
would it be difficult to have webmarks only require the URL and fetch the `<title>` of the page directly by itself? Or does CORS prevent this?

**Comment by skddc** [comment]
Yes, CORS would prevent this for sites without CORS headers. Which could be mitigated by using e.g. the 5apps proxy service though.

However, I don't see how this feature is worth the implementation effort, when regular users usually have it pre-filled anyway, because they use the bookmarklet. So the question is: is there a particular reason why you dont' use it, and which might prevent others from doing so?

**Comment by fkooman** [comment]
I don't use the bookmarklet because it takes another row in my browser (Firefox) to display it. I don't use the "Bookmarks Toolbar". So far I haven't found a way to use bookmarkets without displaying the toolbar unfortunately.

**Comment by skddc** [comment]
I also don't use the toolbar. I just press ctrl-b to open and close the bookmarks list as sidebar, when I want to get to my bookmarklets and often-used browser bookmarks.

**Comment by fkooman** [comment]
Thanks! Will use that from now on. Very discoverable UX :D

**Comment by skddc** [comment]
Ok, cool. Glad I could help.
