### ISSUE TITLE
Search of tag not functioning

### ISSUE THREAD

**Issue by trank1955** [skddc/webmarks#62]
No answer if I search a tag.
The console displays an error (see at the bottom)
Can You help me?
Thanks
Stefano from Italy

_rs.on ready
webmarks-d361a083d843f6d2225cceb55d52a5a7.js:1:20491
rs.on connected
webmarks-d361a083d843f6d2225cceb55d52a5a7.js:1:20544
[storage] Writing tag list to localStorage ["50+50w","Aaron","Amazon","Calibre","DAC","DDNS","DNS","DVD","Domotica","Hole","LNR","Laharah","Libri","PM10","Peterlini","Pi","Python","Raspberry","Raspberry Pi","Raspi","Raspy","Sergio","Server","Swartz","Vimeo","accedere","accesso","acquisti","amplificatore","autore","biblioteca","bird","blocco","blog","bluetooth","book","books","calibre","catalogo","cd","cinema","comandi","control","controllo","copertina","copertine","debian","descrizione","diritto","disabilitare","documentazione","doppiaggio","download","ebay","editor","elegiant","film","find","forwarding","fusione fredda","giornali","gratis","hifi","informatico","inquinamento","lastampa","lettera22","libreria","libri","libro","limes","linux","ma video","manuale","meditazione","micromega","misurazione","naked","news","no-ip","noip","noleggio","notizie","online","panel","pannello","politica","polveri","port","porte","pubblicità","python","raspberry","raspi","raspy","rent","rivista","rocco","scheda","scienze","server","shopping","sinossi","software","sottili","spiritualità","stampa","streaming","temperatura","terminale","torino","touchpad","trovare","uccello","zeus"]
webmarks-d361a083d843f6d2225cceb55d52a5a7.js:1:21300
**TypeError: n.title is undefined**[Ulteriori informazioni]
webmarks-d361a083d843f6d2225cceb55d52a5a7.js:1:6664_

**Comment by skddc** [comment]
Hi Stefano,

It looks like for some reason you have a bookmark object stored without a title. It could be from another app, because Webmarks validates that a title is entered usually.

I changed the code so that it doesn't load invalid bookmark objects into the list anymore, so it also doesn't fail when searching tags (where it's trying to search the titles). If you check the console, you will see a warning log, which contains the invalid bookmark that was causing the problem.

Thanks for reporting this issue. Let me know if my fix works for you.
